name: Release DERP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出源码
      - uses: actions/checkout@v4
      
      # 设置 Go 环境
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      # 交叉编译 DERP 服务器
      - name: Cross building DERP server
        run: |
          mkdir -p .build
          # 编译不同架构的二进制文件
          CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w" -o .build/derp-linux-amd64 ./cmd/derper
          CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -ldflags="-s -w" -o .build/derp-linux-arm64 ./cmd/derper
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o .build/derp-windows-amd64.exe ./cmd/derper
          CGO_ENABLED=0 GOOS=linux   GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-s -w" -o .build/derp-linux-mipsle ./cmd/derper
          CGO_ENABLED=0 GOOS=linux   GOARCH=mips   GOMIPS=softfloat go build -ldflags="-s -w" -o .build/derp-linux-mips ./cmd/derper
          CGO_ENABLED=0 GOOS=linux   GOARCH=arm    go build -ldflags="-s -w" -o .build/derp-linux-arm ./cmd/derper

      # 下载 UPX 并进行压缩
      - name: Compress binaries with UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
          tar -xJf upx-4.2.2-amd64_linux.tar.xz --strip-components=1 -C .build
          chmod +x .build/upx
          
          # 使用 UPX 压缩所有二进制文件
          chmod +x .build/*
          .build/upx --ultra-brute .build/*

      # 生成 Release 说明文件
      - name: Generate release body and checksums
        run: |
          echo '**Build At**:
          
          * `'"$(date)"'`
          * `'"$(TZ=Asia/Shanghai date)"'`
          
          **sha256sum**:

          ```-
          '"$(cd .build && sha256sum *)"'
          ```' > body.md

      # 创建发布
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release DERP Server
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          artifacts: .build/*
          commit: main
          tag: derp-release-main-latest
          bodyFile: body.md
